import Head from "next/head";
import Image from "next/image";
import Logo from "./images/Logo.png";
import PortFolio1 from "./images/portfolio1.png";
import portfoli2 from "./images/portfolio2.png";
import maket3 from "./images/maket3.png";
import statistika from "./images/statistika.png";
import statistika2 from "./images/statistika2.png";
import bot from "./images/Telegram.png";
import crm from "./images/crm.png";
import phone from "./images/phone.png";
import dizayn from "./images/dizayn.png";
import graf from "./images/graf.png";
import saytlar from "./images/sayt-logo.png";
import { AiOutlineLeft } from "react-icons/ai";
import { AiOutlineRight } from "react-icons/ai";
import { MdOutlinePhone } from "react-icons/md";
import Goal from "./images/business-goal.png";
import Tools from "./images/repair-tool.png";
import Slider from "../components/Slider";
import Modal from "@/components/modal";
import { useGlobalContext } from "../context";
import Accordion from "@/components/Accordion";

export default function Home() {
  const { showModal, setShowModal } = useGlobalContext();
  return (
    <div className="bg-[#F9FBFC] scroll-smooth w-full">
      <Head>
        <title>Programmer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-[300px] md:w-[800px] lg:w-[1000px] mx-auto pt-5">
        <div className="flex border  border-[#D7E0E8] rounded-[30px] sm:items-center p-2">
          <Image src={Logo} alt=",.," width={100} height={100} className="" />
          <ul className="lg:flex mx-auto text-[17px] md:flex hidden m-0">
            <li className="mx-[20px] ">
              <a className=" text-black" href="#portfolio">
                Portfolio
              </a>
            </li>
            <li className="mx-[20px]">
              <a href="#services" className=" text-black">
                Bizning xizmatlarimiz
              </a>
            </li>
            <li className="mx-[20px] ">
              <a href="#founders" className="text-black">
                Hamkorlar
              </a>
            </li>
          </ul>
          <button
            type="tell"
            className="ml-7 sm:ml-0 flex items-center sm:mr-4 text-[12px] sm:text-[16px]"
          >
            <MdOutlinePhone className="mr-3" />
            <p className="m-0">+998 97 628 28 82</p>
          </button>
        </div>
        <div className="mx-auto text-center mt-10">
          <p className="text-[17px]">
            Biznesingizni keyingi bosqichga olib chiqish yoki
            g&apos;oyalaringizni binzesga aylantirish haqida
            qayg&apos;uryapsizmi?
          </p>
          <h1 className="text-[#0D0C0F] text-[40px] md:text-[60px]">
            <span className="text-[#0677E1]">Programmist.uz</span> bilan
            tanishing
          </h1>
          <p className="text-[17px]">
            Hurmat bilan, Mijozlar muammosiga IT orqali yechim beruvchi jamoa!
          </p>
          {showModal ? <Modal /> : ""}
          <button
            onClick={() => setShowModal(true)}
            className="mt-3 bg-[#0677E1] rounded-xl px-[60px] py-[14px] text-white bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]"
          >
            Bepul konsultatsiya olish
          </button>
          <div className="flex overflow-auto mt-10 flex-wrap">
            <Image
              src={PortFolio1}
              alt="maket1"
              className="w-[300px] md:w-[650px] md:h-[550px]"
            />
            <div className="reletive flex">
              <Image
                alt="maket2"
                src={portfoli2}
                className="w-[200px] sm:w-[300px] md:h-[520px] ml-4 z-[1]"
              />
              <Image
                alt="maket3"
                src={maket3}
                className="w-[200px] sm:w-[300px] right-[85px] z-[0] absolute md:right-[100px] mt-[20px] md:h-[520px]"
              />
            </div>
          </div>
        </div>
      </div>
      <section id="portfolio">
        <div className="lg:w-[1000px] mx-auto md:mt-10">
          <h1 className="mt-10 sm:mt-0 text-[30px] md:text-[40px] text-center font-[700]">
            Bizning{" "}
            <span className="bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
              statistika
            </span>{" "}
          </h1>
          <div className="flex justify-center mt-8 flex-wrap">
            <div className="bg-white border w-[150px] sm:w-[280px] rounded-[18px]  text-center h-[150px]">
              <h2 className="text-[30px] sm:text-[40px] font-[700] mt-8">3+</h2>
              <p>Yillik tajriba</p>
            </div>
            <div className="bg-white border w-[150px] sm:w-[280px] rounded-[18px]  mx-5 text-center h-[150px]">
              <h2 className="text-[30px] sm:text-[40px] font-[700] mt-8">
                13 +
              </h2>
              <p>Loyihalar</p>
            </div>
            <div className="mt-4 lg:mt-0 bg-white border w-[320px] sm:w-[280px] rounded-[18px]  text-center h-[150px]">
              <h2 className="text-[30px] sm:text-[40px] font-[700] mt-8">
                13 +
              </h2>
              <p>Mutaxxasislar</p>
            </div>
          </div>
        </div>
        <div className="border bg-white rounded-[32px] flex w-[350px] md:w-[600px] lg:w-[1000px] flex-wrap mx-auto mt-20 justify-between ">
          <div className="sm:w-[450px] ml-[70px] sm:mt-[70px] mt-[40px]">
            <p className="uppercase font-[700]">
              Bizning{" "}
              <span className="bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
                portfolio
              </span>
            </p>
            <h2 className="text-[25px] sm:text-[32px] font-[700]">
              Lorem Ipsum is simply
            </h2>
            <p className="mt-7 w-[280px] sm:w-auto">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry&apos;s standard dummy
              text ever since the 1500s,
            </p>
            <div className="flex justify-between mt-8 flex-wrap  sm:flex-auto">
              <button className="flex ml-5 w-[350px] text-center sm:w-auto  font-[600] items-center rounded-xl bg-[#F0F4F8] py-[14px] px-5 bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
                Loyihani ko&apos;rish{" "}
                <AiOutlineRight className="text-[12px] ml-2 text-[#8C1FE2]" />
              </button>
              <div className="text-center ml-[60px] sm:ml-0 sm:mr-0">
                <button className="text-[12px] mr-4 hover:text-white w-10 h-10 rounded-[40px] hover:bg-gradient-to-r hover:from-sky-600 hover:to-indigo-700">
                  <AiOutlineLeft className="ml-[14px]" />
                </button>
                <button className="text-[12px] hover:text-white text-center w-10 h-10 rounded-[40px] hover:bg-gradient-to-r hover:from-sky-600 hover:to-indigo-700">
                  <AiOutlineRight className="ml-[14px]  font-bold" />
                </button>
              </div>
            </div>
          </div>
          <div className="flex sm:mt-8 mb-5 sm:mb-0 ml-4">
            <Image
              src={statistika}
              alt="statistika"
              className="w-[330px] sm:w-[400px] md:w-[600px] z-[2] mt-6 lg:w-[400px]"
            />
            <Image
              src={statistika2}
              alt="statistika2"
              className="absolute w-[330px]  sm:w-[400px] md:w-[580px] lg:w-[400px]"
            />
          </div>
        </div>
      </section>
      <section className="bg-white rounded-[40px] mt-20 " id="services">
        <div className="lg:w-[1000px] md:w-[800px ] mx-auto">
          <h1 className="text-center text-[30px] md:text-[40px] font-[700] ">
            Bizning{" "}
            <span className="bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
              xizmatlar
            </span>{" "}
          </h1>
          <div className="flex flex-wrap mx-auto justify-center text-center">
            <div className="w-[150px] sm:w-[300px] h-[150px] sm:h-[200px] flex flex-col items-center justify-center bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image className="" src={saytlar} alt="saytlar" />
              </div>
              <p className="mt-2">Vebsayt yaratish</p>
            </div>
            <div className="w-[150px] sm:w-[300px] h-[150px] sm:h-[200px] flex flex-col items-center justify-center bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image src={crm} alt="CRM" />
              </div>
              <p className="mt-2">CRM</p>
            </div>
            <div className="w-[150px] sm:w-[300px] h-[150px] sm:h-[200px] flex flex-col items-center justify-center bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image src={bot} alt="telegram" />
              </div>
              <p className="mt-2">Telegram bot</p>
            </div>
            <div className="w-[150px] sm:w-[300px] h-[150px] sm:h-[200px] flex flex-col items-center justify-center bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image src={phone} alt="phone" />
              </div>
              <p className="mt-2">Mobile ilovalar</p>
            </div>
            <div className="w-[150px] sm:w-[300px] flex flex-col items-center justify-center h-[150px] sm:h-[200px] bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image src={dizayn} alt="grafic dizayn" />
              </div>
              <p className="mt-2">Grafik dizayn</p>
            </div>
            <div className="w-[150px] sm:w-[300px] place-items-center flex-col flex justify-center h-[150px] sm:h-[200px] bg-[#F8FBFE] m-2 rounded-[18px] border">
              <div className="w-20 h-20 rounded-[80px] bg-[#ECEBFC] place-items-center flex justify-center">
                <Image src={graf} alt="UI UX dizayn" />
              </div>
              <p className="mt-2">UX/UI Dizayn</p>
            </div>
          </div>

          <button
            onClick={() => setShowModal(true)}
            className="text-center text-white rounded-xl mt-5 sm:mt-[60px] block mx-auto px-[60px] py-[14px] bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]"
          >
            Bepul konsultatsiya olish
          </button>
        </div>
      </section>
      <section id="founders">
        <div className=" md:w-[1000px] mx-auto mt-10 md:mt-[150px]">
          <h1 className="text-center text-[30px]  md:text-[40px] font-[700] ">
            Bizning{" "}
            <span className="bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
              hamkorlar
            </span>{" "}
          </h1>
          <Slider />
          <div className="mt-20 flex flex-wrap  justify-center ">
            <h2 className="text-[30px] md:text-[40px] text-center w-[300px] sm:w-[400px] md:w-[500px] lg:w-[400px] font-[700]">
              Eng ko&apos;p beriladigan{" "}
              <span className="text-[#8C1FE2] ">savollar</span>{" "}
            </h2>
            <div>
              <Accordion />
            </div>
          </div>
        </div>
      </section>

      <footer className="md:w-[1000px] mx-auto md:h-[300px] flex-wrap justify-around bg-white rounded-[40px] flex">
        <div className="mt-10">
          <Image src={Goal} alt="business goal" />
        </div>
        <div className="w-[300px] md:w-[500px] flex flex-col justify-center items-center">
          <h2 className="text-[30px] md:text-[50px] font-[700]  ">
            O&apos;ylab{" "}
            <span className="bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]  bg-clip-text text-transparent">
              ko&apos;ring!
            </span>{" "}
          </h2>
          <p className="text-center px-7 my-6">
            Biznesingizni keyingi bosqichga olib chiqish yoki
            g&apos;oyalaringizni biznesga aylantirish haqida
            qayg&apos;uryapsizmi?
          </p>
          <button
            onClick={() => setShowModal(true)}
            className=" text-white rounded-xl py-[14px] px-[60px] bg-gradient-to-r from-[#0677E1] to-[#8C1FE2]"
          >
            Bepul konsultatsiya olish
          </button>
        </div>
        <div className="md:mt-[120px]">
          <Image src={Tools} alt="repair tools" />
        </div>
      </footer>
      <div className="mt-10 w-[300px] text-center flex-wrap rounded-[30px] mb-4 md:w-[800px] lg:w-[1000px] py-2 mx-auto justify-between flex bg-white items-center">
        <p></p>
        <p className="m-0">www.programmist.uz Barcha huquqlar himoyalangan</p>
        <button
          type="tell"
          className="flex items-center ml-[70px] sm:ml-0 md:mr-10"
        >
          <MdOutlinePhone className="mr-3 text-center" /> +998 97 628 28 82
        </button>
      </div>
    </div>
  );
}
